[0.000000] (-) TimerEvent: {}
[0.001339] (-) JobUnselected: {'identifier': 'follow_objects'}
[0.001512] (-) JobUnselected: {'identifier': 'py_pubsub'}
[0.001674] (follow_obj2) JobQueued: {'identifier': 'follow_obj2', 'dependencies': OrderedDict()}
[0.001774] (follow_obj2) JobStarted: {'identifier': 'follow_obj2'}
[0.097164] (-) TimerEvent: {}
[0.198210] (-) TimerEvent: {}
[0.299782] (-) TimerEvent: {}
[0.401502] (-) TimerEvent: {}
[0.504750] (-) TimerEvent: {}
[0.605476] (-) TimerEvent: {}
[0.706832] (-) TimerEvent: {}
[0.807565] (-) TimerEvent: {}
[0.908975] (-) TimerEvent: {}
[1.010501] (-) TimerEvent: {}
[1.112068] (-) TimerEvent: {}
[1.213626] (-) TimerEvent: {}
[1.315223] (-) TimerEvent: {}
[1.417872] (-) TimerEvent: {}
[1.481178] (follow_obj2) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build\n    setup_py_data = get_setup_data(self.context.pkg, env)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/__init__.py", line 20, in get_setup_data\n    return dict(pkg.metadata[key](env))\n  File "/usr/lib/python3/dist-packages/colcon_ros/package_augmentation/ros_ament_python.py", line 57, in getter\n    return get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 241, in get_setup_information\n    _setup_information_cache[hashable_env] = _get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 288, in _get_setup_information\n    result = subprocess.run(\n  File "/usr/lib/python3.10/subprocess.py", line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/python3\', \'-c\', \'import sys;from contextlib import suppress;exec("with suppress(ImportError):    from setuptools.extern.packaging.specifiers    import SpecifierSet");exec("with suppress(ImportError):    from packaging.specifiers import SpecifierSet");from distutils.core import run_setup;dist = run_setup(    \\\'setup.py\\\', script_args=(\\\'--dry-run\\\',), stop_after=\\\'config\\\');skip_keys = (\\\'cmdclass\\\', \\\'distclass\\\', \\\'ext_modules\\\', \\\'metadata\\\');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith(\\\'_\\\') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data[\\\'metadata\\\'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in (\\\'license_files\\\', \\\'provides_extras\\\')};sys.stdout.buffer.write(repr(data).encode(\\\'utf-8\\\'))\']\' returned non-zero exit status 1.\n'}
[1.483135] (follow_obj2) JobEnded: {'identifier': 'follow_obj2', 'rc': 1}
[1.492462] (-) EventReactorShutdown: {}
